@startuml BT Receiver


[*] --> NonDiscoverable : Initialise()

state NonDiscoverable {

    [*] --> Disconnected
    state Disconnected  {
        [*] -> Connectable

        Connectable --> Authenticating : Connection Attempt
        Authenticating -> Connectable : [Failure]
        Authenticating -> Connected : [Success]

    }

    state Connected {
        [*] --> AwaitingCommand

    }

    Connected --> Disconnected : Disconnect()
}

NonDiscoverable ----> Discoverable : [Discovery Button Press]

state Discoverable{
    [*] --> Waiting
    Waiting --> Pairing : [Pair Request]
    Pairing --> Connected : [Paired]
    Pairing --> Waiting : [Failure]
}

Discoverable -u--> NonDiscoverable : [Timeout]

@enduml